In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/clean/AirBnbDataClean.csv')

df.describe()

,Unnamed: 0,id,host id,lat,long,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,84313.000000,8.431300e+04,8.431300e+04,84313.000000,84313.000000,84313.000000,84313.000000,84313.000000,84313.000000,84313.000000,84313.000000,84313.000000,84313.000000,84313.000000
mean,52118.434180,2.959593e+07,4.917181e+10,40.727354,-73.948504,2012.485951,626.042710,125.209588,7.428665,32.206682,1.375162,3.280075,7.031075,141.871076
std,29525.742692,1.620379e+07,2.853124e+10,0.056344,0.050358,5.760817,331.688758,66.341272,27.986974,51.835655,1.747645,1.282812,29.467339,133.922716
min,0.000000,1.001254e+06,1.236005e+08,40.504560,-74.249840,2003.000000,50.000000,10.000000,-365.000000,1.000000,0.010000,1.000000,1.000000,-10.000000
25%,26333.000000,1.547601e+07,2.443182e+10,40.687670,-73.982110,2007.000000,340.000000,68.000000,2.000000,3.000000,0.220000,2.000000,1.000000,6.000000
50%,54295.000000,3.082830e+07,4.900886e+10,40.721330,-73.953720,2012.000000,625.000000,125.000000,3.000000,11.000000,0.740000,3.000000,1.000000,101.000000
75%,77082.000000,4.327824e+07,7.383948e+10,40.762610,-73.930830,2017.000000,914.000000,183.000000,5.000000,38.000000,2.010000,4.000000,2.000000,266.000000
max,102597.000000,5.735803e+07,9.876313e+10,40.916970,-73.705220,2022.000000,1200.000000,240.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

# Tendencia central

In [ ]:
def media(data):
  n = len(data)
  sum = 0
  for i in data:
    sum += i
  return sum / n

def mediana(data):
  n = len(data)